metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
    - filesystem
    - fsstat
  enabled: true
  period: 10s
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  process.include_per_cpu: true

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

- module: postgresql
  metricsets:
    - database
    - activity
    - bgwriter
  hosts: ["postgresql://order_user:order_password@postgres:5432/order_process?sslmode=disable"]
  period: 10s
  enabled: true

- module: redis
  metricsets:
    - info
  hosts: ["redis:6379"]
  period: 10s
  enabled: true

# - module: rabbitmq
#   metricsets:
#     - node
#     - overview
#     - queue
#     - connection
#     - exchange
#   hosts: ["rabbitmq:15672"]
#   username: "order_user"
#   password: "order_password"
#   period: 10s
#   enabled: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded

