http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.enabled: true
xpack.management.enabled: false
# Using file-based pipeline configuration mounted at /usr/share/logstash/pipeline/logstash.conf

